### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by April-8** [UCTRONICS/Smart-Robot-Car-Arduino#4]
anyone getting this error message 
Arduino: 1.8.3 (Windows 10), Board: "Arduino/Genuino Uno"

C:\Users\Jamison\Desktop\Smart-Robot-Car-Arduino-master\UCTRONICS_Smart_Robot_Car\example\NECTest\NECTest.ino:11:19: fatal error: UCNEC.h: No such file or directory

 #include "UCNEC.h"

                   ^

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by per1234** [comment]
This is a library. You need to install it:
(In the Arduino IDE) Sketch -> Include Library -> Add .ZIP Library... -> select C:\Users\Jamison\Desktop\Smart-Robot-Car-Arduino-master\UCTRONICS_Smart_Robot_Car -> Open

**Comment by April-8** [comment]
thanks
